apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: ac-cicd-pipeline
  labels:
    app: cicd
description: cicd delivery pipeline
serialPipeline:
  stages:
  - targetId: prod
  #   profiles:
  #   - prod