# Deployment Configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app-deployment-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ac-laboratory-v1
  template:
    metadata:
      labels:
        app: ac-laboratory-v1
    spec:
      containers:
      - name: ac-laboratory-v1
        image: us-central1-docker.pkg.dev/natural-potion-423808-h2/repo/quickstart-image:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"    # Reduced from previous value
            memory: "128Mi"
          limits:
            cpu: "200m"    # Reduced from previous value
            memory: "256Mi"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2


---
# Service Configuration
apiVersion: v1
kind: Service
metadata:
  name: ac-laboratory-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: ac-laboratory-v1

---
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ac-laboratory-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloud-app-deployment-v1
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
