apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app-deployment
spec:
  replicas: 3 # Number of instances of the application
  selector:
    matchLabels:
      app: ac-laboratory-v1
  template:
    metadata:
      labels:
        app: ac-laboratory-v1
    spec:
      containers:
      - name: ac-laboratory-v1
        image: us-central1-docker.pkg.dev/ac-m-laborator-clean/gke-repo/cloud-app:latest
        ports: 
        - containerPort: 8080
  strategy: # update w\o downtime
    type: RollingUpdate
    rollingUpdate:
        maxUnavailable: 0
        maxSurge: 2

apiVersion: v1
kind: Service
metadata:
  name: ac-laboratory-service
spec:
  type: LoadBalancer
  ports:
  - port: 80 # Expose the service on internal port 80
    targetPort: 8080 # Send the traffic to container port 8080
  selector:
    app: ac-laboratory-v1